# This simple site config YAML file is capable of executing tests which use the
# local Docker instance for containerized tests, and publish results to a local
# directory. It's an easy way to try out PAPR!

backends:
  container:
    type: docker

publisher:
  type: local
  config:
    rootdir: /var/tmp/papr
